"""empty message

Revision ID: 60fbd15c8dbb
Revises: 8960dbe869b3
Create Date: 2019-05-11 18:20:03.533114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fbd15c8dbb'
down_revision = '8960dbe869b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_next_run_time', table_name='tasks')
    op.drop_table('tasks')
    op.add_column('subscription', sa.Column('output', sa.Text(), nullable=True))
    op.create_index(op.f('ix_subscription_output'), 'subscription', ['output'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_output'), table_name='subscription')
    op.drop_column('subscription', 'output')
    op.create_table('tasks',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_next_run_time', 'tasks', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
