"""empty message

Revision ID: 6f19a4da2349
Revises: 9e4c853edd7a
Create Date: 2019-04-19 23:24:16.950647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f19a4da2349'
down_revision = '9e4c853edd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_city'), 'records', ['city'], unique=False)
    op.create_index(op.f('ix_records_doc_type'), 'records', ['doc_type'], unique=False)
    op.create_index(op.f('ix_records_name'), 'records', ['name'], unique=False)
    op.create_index(op.f('ix_records_path'), 'records', ['path'], unique=False)
    op.drop_index('ix_record_city', table_name='record')
    op.drop_index('ix_record_doc_type', table_name='record')
    op.drop_index('ix_record_name', table_name='record')
    op.drop_index('ix_record_path', table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.Column('doc_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date', sa.VARCHAR(length=64), nullable=True),
    sa.Column('path', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_record_path', 'record', ['path'], unique=False)
    op.create_index('ix_record_name', 'record', ['name'], unique=False)
    op.create_index('ix_record_doc_type', 'record', ['doc_type'], unique=False)
    op.create_index('ix_record_city', 'record', ['city'], unique=False)
    op.drop_index(op.f('ix_records_path'), table_name='records')
    op.drop_index(op.f('ix_records_name'), table_name='records')
    op.drop_index(op.f('ix_records_doc_type'), table_name='records')
    op.drop_index(op.f('ix_records_city'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
