"""empty message

Revision ID: 8960dbe869b3
Revises: cd161d249184
Create Date: 2019-05-11 17:39:10.207143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8960dbe869b3'
down_revision = 'cd161d249184'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_next_run_time', table_name='tasks')
    op.drop_table('tasks')
    op.add_column('subscription', sa.Column('frequency', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_subscription_frequency'), 'subscription', ['frequency'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_frequency'), table_name='subscription')
    op.drop_column('subscription', 'frequency')
    op.create_table('tasks',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_next_run_time', 'tasks', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
