"""empty message

Revision ID: 9e0ac9c5f435
Revises: 60fbd15c8dbb
Create Date: 2019-05-11 18:23:06.631956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0ac9c5f435'
down_revision = '60fbd15c8dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_next_run_time', table_name='tasks')
    op.drop_table('tasks')
    op.add_column('subscription', sa.Column('total', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subscription_total'), 'subscription', ['total'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_total'), table_name='subscription')
    op.drop_column('subscription', 'total')
    op.create_table('tasks',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_next_run_time', 'tasks', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
