"""empty message

Revision ID: 9e4c853edd7a
Revises: 2eda2e568ba7
Create Date: 2019-04-19 22:51:13.411377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4c853edd7a'
down_revision = '2eda2e568ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_city'), 'record', ['city'], unique=False)
    op.create_index(op.f('ix_record_doc_type'), 'record', ['doc_type'], unique=False)
    op.create_index(op.f('ix_record_name'), 'record', ['name'], unique=False)
    op.create_index(op.f('ix_record_path'), 'record', ['path'], unique=False)
    op.drop_table('sub')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('keyword', sa.VARCHAR(length=140), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_record_path'), table_name='record')
    op.drop_index(op.f('ix_record_name'), table_name='record')
    op.drop_index(op.f('ix_record_doc_type'), table_name='record')
    op.drop_index(op.f('ix_record_city'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
