"""empty message

Revision ID: dcb7d41a07f7
Revises: 
Create Date: 2019-04-23 23:44:10.636437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb7d41a07f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('doctype', sa.String(length=64), nullable=True),
    sa.Column('date', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_body'), 'records', ['body'], unique=False)
    op.create_index(op.f('ix_records_city'), 'records', ['city'], unique=False)
    op.create_index(op.f('ix_records_doctype'), 'records', ['doctype'], unique=False)
    op.create_index(op.f('ix_records_name'), 'records', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_organization'), 'user', ['organization'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_organization'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_records_name'), table_name='records')
    op.drop_index(op.f('ix_records_doctype'), table_name='records')
    op.drop_index(op.f('ix_records_city'), table_name='records')
    op.drop_index(op.f('ix_records_body'), table_name='records')
    op.drop_table('records')
    # ### end Alembic commands ###
